### ISSUE TITLE
Handle deposits with not enough SDs (NTs and/or NFTs)

### ISSUE THREAD

**Issue by jorgemmsilva** [iotaledger/wasp-legacy#2067]
```
2023-03-07T10:23:14Z	DEBUG	Chains.0x793f158a.C-0xb7565301.LI-6.VM	debit from tst1qq2m4ck6sd5q0tenmp86y7w55938gt83yn3d0r9u28sx5c7xzcerzv9kze8: not enough funds
assets: base tokens: 4396000
2023-03-07T10:23:14Z	DEBUG	Chains.0x793f158a.C-0xb7565301.LI-6.VM	goroutine 614 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/iotaledger/wasp/packages/util/panicutil.CatchAllButDBError.func1.1()
	/scratch/packages/util/panicutil/panicutil.go:57 +0x270
panic({0x2b6d6a0, 0xc0023c37f0})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/iotaledger/wasp/packages/util/panicutil.CatchPanicReturnError.func1.1()
	/scratch/packages/util/panicutil/panicutil.go:30 +0x137
panic({0x2b6d6a0, 0xc0023c37f0})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/iotaledger/wasp/packages/util/panicutil.CatchPanicReturnError.func1.1()
	/scratch/packages/util/panicutil/panicutil.go:30 +0x137
panic({0x2b6d6a0, 0xc0023c37f0})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/iotaledger/wasp/packages/vm/core/accounts.DebitFromAccount({0x33770d8, 0xc001961fe0}, {0x3362b40?, 0xc0023c3350?}, 0xc0008ac900)
	/scratch/packages/vm/core/accounts/fungibletokens.go:57 +0x1da
github.com/iotaledger/wasp/packages/vm/core/accounts.AdjustAccountBaseTokens({0x33770d8, 0xc001961fe0}, {0x3362b40, 0xc0023c3350}, 0xffffffffffbcec20)
	/scratch/packages/vm/core/accounts/basetokens.go:26 +0x632
github.com/iotaledger/wasp/packages/vm/vmcontext.(*VMContext).adjustL2BaseTokensIfNeeded.func1.1({0x33770d8?, 0xc001961fe0?})
	/scratch/packages/vm/vmcontext/internal.go:225 +0x2f
github.com/iotaledger/wasp/packages/vm/vmcontext.(*VMContext).callCore(0xc00094b100, 0x77c07f6cc55f6e75?, 0xc002699798)
	/scratch/packages/vm/vmcontext/call.go:106 +0x173
github.com/iotaledger/wasp/packages/vm/vmcontext.(*VMContext).adjustL2BaseTokensIfNeeded.func1()
	/scratch/packages/vm/vmcontext/internal.go:224 +0x68
github.com/iotaledger/wasp/packages/util/panicutil.CatchPanicReturnError.func1({0xc002699878?, 0x4?, 0x8?}, 0x3c4b5e0200000000?, 0x4?)
	/scratch/packages/util/panicutil/panicutil.go:32 +0x77
github.com/iotaledger/wasp/packages/util/panicutil.CatchPanicReturnError(0xc00094b100?, {0xc002699878?, 0xc0026998b0?, 0x135b1a5?})
	/scratch/packages/util/panicutil/panicutil.go:33 +0x35
github.com/iotaledger/wasp/packages/vm/vmcontext.(*VMContext).adjustL2BaseTokensIfNeeded(0xc0029b4e60?, 0x3362b40?, {0x3362b40?, 0xc0023c3350?})
	/scratch/packages/vm/vmcontext/internal.go:223 +0x9b
github.com/iotaledger/wasp/packages/vm/vmcontext.(*VMContext).creditAssetsToChain(0xc00094b100)
	/scratch/packages/vm/vmcontext/runreq.go:118 +0x1c5
github.com/iotaledger/wasp/packages/vm/vmcontext.(*VMContext).RunTheRequest.func3()
	/scratch/packages/vm/vmcontext/runreq.go:67 +0x45
github.com/iotaledger/wasp/packages/util/panicutil.CatchPanicReturnError.func1({0x453a8c0?, 0xc000121710?, 0x488eed0?}, 0xc0001216e0?, 0x488eed0?)
	/scratch/packages/util/panicutil/panicutil.go:32 +0x77
github.com/iotaledger/wasp/packages/util/panicutil.CatchPanicReturnError(0xc000884f00?, {0x453a8c0?, 0x5?, 0xc001330710?})
	/scratch/packages/util/panicutil/panicutil.go:33 +0x35
github.com/iotaledger/wasp/packages/vm/vmcontext.(*VMContext).RunTheRequest(0xc00094b100, {0x3376fc8?, 0xc0029b4e60}, 0x0)
	/scratch/packages/vm/vmcontext/runreq.go:64 +0x4a8
github.com/iotaledger/wasp/packages/vm/runvm.runTask(0xc0007f87e0)
	/scratch/packages/vm/runvm/runtask.go:45 +0x105
github.com/iotaledger/wasp/packages/vm/runvm.VMRunner.Run.func1()
	/scratch/packages/vm/runvm/runtask.go:20 +0x1d
github.com/iotaledger/wasp/packages/util/panicutil.CatchAllButDBError.func1(0x7fca1ddcec08?, 0x7fca54c1a3c8?, {0x0?, 0xc000a80000?}, 0xc000aa7f90?)
	/scratch/packages/util/panicutil/panicutil.go:59 +0x77
github.com/iotaledger/wasp/packages/util/panicutil.CatchAllButDBError(0xc000b03040?, 0x4?, {0x0?, 0x846f94?, 0xc0006bff30?})
	/scratch/packages/util/panicutil/panicutil.go:60 +0x49
github.com/iotaledger/wasp/packages/vm/runvm.VMRunner.Run({}, 0xc0007f87e0)
	/scratch/packages/vm/runvm/runtask.go:19 +0x4c
github.com/iotaledger/wasp/packages/chain/cons/gr.(*vmAsync).run(0xc0006bffd0?, 0xc0007f87e0, 0xc0001f8d20?)
	/scratch/packages/chain/cons/gr/vmAsync.go:30 +0x2f
created by github.com/iotaledger/wasp/packages/chain/cons/gr.(*vmAsync).ConsensusRunTask
	/scratch/packages/chain/cons/gr/vmAsync.go:25 +0xaa

2023-03-07T10:23:14Z	WARN	Chains.0x793f158a.C-0xb7565301.LI-6.VM	GENERAL VM EXCEPTION: the task has been abandoned due to: debit from tst1qq2m4ck6sd5q0tenmp86y7w55938gt83yn3d0r9u28sx5c7xzcerzv9kze8: not enough funds
assets: base tokens: 4396000
```

**Comment by dessaya** [comment]
A similar panic can be reproduced with this test:

```
func TestDepositNFT(t *testing.T) {
	env := solo.New(t, &solo.InitOptions{AutoAdjustStorageDeposit: false, Debug: true, PrintStackTrace: true})
	ch := env.NewChain()

	// mint an NFT and send it to the chain
	issuerWallet, issuerAddress := env.NewKeyPairWithFunds()
	nft, _, err := env.MintNFTL1(issuerWallet, issuerAddress, []byte("foobar"))
	require.NoError(t, err)
	req := solo.NewCallParams(accounts.Contract.Name, accounts.FuncDeposit.Name).
		AddBaseTokens(2580).
		WithNFT(nft).
		WithMaxAffordableGasBudget().
		WithSender(nft.ID.ToAddress())
	require.NoError(t, err)
	_, err = ch.PostRequestSync(req, issuerWallet)
	require.NoError(t, err)
}
```

**Comment by dessaya** [comment]
This one produces the same stack trace as the reported issue:

```
func TestDepositNFT(t *testing.T) {
	env := solo.New(t, &solo.InitOptions{AutoAdjustStorageDeposit: false, Debug: true, PrintStackTrace: true})
	ch := env.NewChain()

	issuerWallet, issuerAddress := env.NewKeyPairWithFunds()
	nft, _, err := env.MintNFTL1(issuerWallet, issuerAddress, []byte("foobar"))
	require.NoError(t, err)
	req := solo.NewCallParams(accounts.Contract.Name, accounts.FuncDeposit.Name).
		WithNFT(nft).
		AddBaseTokens(2580).
		WithMaxAffordableGasBudget().
		WithSender(nft.ID.ToAddress())

	ch.TransferAllowanceTo(isc.NewAssetsBaseTokens(100_000), isc.NewContractAgentID(ch.ChainID, 0), issuerWallet)
	t.Log(ch.L2TotalAssets())

	_, err = ch.PostRequestSync(req, issuerWallet)
	require.ErrorContains(t, err, "gas")
}
```
