### ISSUE TITLE
goroutines accumulate on validator nodes

### ISSUE THREAD

**Issue by shufps** [iotaledger/wasp-legacy#2424]
On nodes participating on the consensus, the goroutines accumulate.

This looks like this:

![image](https://user-images.githubusercontent.com/3079832/236207770-00ef4f77-6d3f-41f8-8fc8-a5d753985000.png)

PProf shows this goroutine (300k times):

```
goroutine 1835983 [select, 9694 minutes]:
github.com/iotaledger/wasp/packages/util/pipe.(*InfinitePipe[...]).infiniteBuffer(0xc0034fe580)
	/scratch/packages/util/pipe/pipe.go:82 +0x117
created by github.com/iotaledger/wasp/packages/util/pipe.newInfinitePipe[...]
	/scratch/packages/util/pipe/pipe.go:55 +0x158
```

This leads to slow death of OOM if not fixed.

**Comment by shufps** [comment]
huh ... `shufps assigned fijter...` ... I didn't do it :flushed: :innocent: 

oh or happens this automatically? :thinking:
