### ISSUE TITLE
Local Setup doesn't work

### ISSUE THREAD

**Issue by kthecoder** [iotaledger/wasp-legacy#2643]
**Describe the bug**
The containers boot up and run and connect. The dashboards open. But the endpoints aren't reachable and the chain say's it deploys and activates but then I get errors when deploying contracts. The chain doesn't show up on the dashboard, just a loading animation.

Really hoping to get some help with understanding how to debug this issues so I can get to testing smart contracts.

**To Reproduce**

1. Download the lastest release of Wasp
2. Create the necessary docker volumes
3. Run `docker compose up` inside the local-setup folder
4. Run `wasp-cli init` inside the local-setup folder
5. Dashboard shows `No Chains` at this point
6. Run : `wasp-cli set l1.apiaddress http://localhost:14265`
7. Run: `wasp-cli set l1.faucetaddress http://localhost:8091`
8. Run `wasp-cli wasp add wasp-0 http://localhost:9090`
9. Run `wasp-cli request-funds`
10. Run : `wasp-cli chain deploy --quorum=1 --chain=testChain`
11. Run: `npx hardhat run scripts/deploy.js` : GIVES ERROR 1X
12. Curl : `localhost/health` : Nothing
13. Curl : `localhost/wasp/api/v1/info` : 2X

1X :
```bash
wasp            | 2023-06-29T16:20:45Z  DEBUG   Chains.0x42ef6482.CM    handleInputCanPropose
wasp            | 2023-06-29T16:20:45Z  DEBUG   Chains.0x42ef6482       handleChainMgrOutput: {chainMgr.Output, LatestConfirmedAliasOutput=nil, NeedConsensus=<nil>, NeedPublishTX=&{map[] 0 0xc000f0c5a0 {{0 0} 0 0 {{} 0} {{} 0}}}}
wasp            | 2023-06-29T16:20:45Z  DEBUG   Chains.0x42ef6482       LatestState(ActiveOrCommittedState) => inStore = <nil>, latest trie root is unknown
wasp            | 2023-06-29T16:20:45Z  ERROR   WebAPI  Internal Server Error: couldn't get latest block index: latest trie root is unknown
wasp            | requestURI: /v1/chains/<chainID>/evm
wasp            |  goroutine 498 [running]:
wasp            | runtime/debug.Stack()
wasp            |       /usr/local/go/src/runtime/debug/stack.go:24 +0x65
```

2X:
```bash
curl : {"Message":"Not Found","Error":""}
```

Hardhat Config File:
```js
module.exports = {
  defaultNetwork: "local",
  networks: {
    hardhat: {
    },
    local: {
      url: "http://localhost/wasp/api/v1/chains/tst1ppwdmgdgxq785sve47cgwvgmqumlzlyhn378p9lxxszj9dymwjlvw8gd7x8/evm/jsonrpc",
      chainId: 1074,
    }
  },
  solidity: { 
    version: "0.8.17",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200
      }
    }
  },
};
```

**Expected behavior**
I expect that the deployed chain would show on the Wasp Dashboard. 
I expect the contract to deploy.

**Network and versioning**
 - Type of L1 network: Localhost
 - Type of Wasp chain: Localhost
 - Interaction method: Wasp-cli, JSON/RPC HTTP, Wasp API, Dashboard
 - Interaction software: Hardhat
 - Version of Wasp : Wasp-cli version 0.6.0-alpha.7
 - 
**Additional context**
If this is just something wrong on my computer. What steps can be taken to debug the issue and get this working?

Thanks.

**Comment by LaKabra** [comment]
tried from wasp/tools/local-setup

> 2023-06-30 12:13:58 panic: Cannot make L1 commitment from previous alias output, error: excess bytes in buffer
2023-06-30 12:13:58 
2023-06-30 12:13:58 goroutine 76 [running]:
2023-06-30 12:13:58 github.com/iotaledger/wasp/packages/chain/statemanager/sm_gpa/sm_inputs.NewChainFetchStateDiff({0x357b230?, 0xc0005fe500}, 0xc000839bd0?, 0xc000a24480)
2023-06-30 12:13:58     /scratch/packages/chain/statemanager/sm_gpa/sm_inputs/chain_fetch_state_diff.go:31 +0x1df
2023-06-30 12:13:58 github.com/iotaledger/wasp/packages/chain/statemanager.(*stateManager).ChainFetchStateDiff(0xc0006548c0, {0x357b230?, 0xc0005fe500?}, 0xc000840250?, 0xff?)
2023-06-30 12:13:58     /scratch/packages/chain/statemanager/state_manager.go:178 +0x34
2023-06-30 12:13:58 github.com/iotaledger/wasp/packages/chain.(*stateTrackerImpl).TrackAliasOutput(0xc00084c880, 0xc000a24480, 0x1)
2023-06-30 12:13:58     /scratch/packages/chain/state_tracker.go:90 +0x2a4
2023-06-30 12:13:58 github.com/iotaledger/wasp/packages/chain.(*chainNodeImpl).handleAliasOutput(0xc000851200, {0x357b230, 0xc0000e4500}, 0xc000a24480)
2023-06-30 12:13:58     /scratch/packages/chain/node.go:706 +0x1b2
2023-06-30 12:13:58 github.com/iotaledger/wasp/packages/chain.(*chainNodeImpl).run(0xc000851200, {0x357b230, 0xc0000e4500}, 0xc00026ac60?)
2023-06-30 12:13:58     /scratch/packages/chain/node.go:540 +0xb15
2023-06-30 12:13:58 created by github.com/iotaledger/wasp/packages/chain.New
2023-06-30 12:13:58     /scratch/packages/chain/node.go:477 +0x2191

**Comment by jorgemmsilva** [comment]
Please try removing the docker volumes and re-create them using the latest wasp/wasp-cli versions
